import { getLogsAll, getAchievements, saveAchievement, getMediaAll } from './db.js';

export async function checkAchievements(showAchievementFn) {
    const logs = await getLogsAll();
    const achievements = await getAchievements();
    const mediaList = await getMediaAll();

    if (logs.length === 0) return;

    const unlockedIds = new Set(achievements.map(a => a.id));

    const unlock = async (id, name, desc) => {
        if (!unlockedIds.has(id)) {
            await saveAchievement({ id, unlockedAt: Date.now() });
            showAchievementFn({ name, desc });
            unlockedIds.add(id);
        }
    };

    const totalMinutes = logs.reduce((sum, l) => sum + (Number(l.durationMinutes) || 0), 0);
    const totalHours = totalMinutes / 60;
    const totalChars = logs.reduce((sum, l) => sum + (Number(l.chars) || 0), 0);
    const completedMediaCount = mediaList.filter(m => m.status === 'completed').length;

    // Streaks
    const dates = [...new Set(logs.map(l => l.date))].sort().reverse();
    let currentStreak = 0;
    const checkDate = new Date();
    const pd = (d) => {
        const p = n => n.toString().padStart(2, '0');
        return `${d.getFullYear()}-${p(d.getMonth() + 1)}-${p(d.getDate())}`;
    };

    // Start from today or yesterday
    if (!dates.includes(pd(checkDate))) {
        checkDate.setDate(checkDate.getDate() - 1);
    }

    while (dates.includes(pd(checkDate))) {
        currentStreak++;
        checkDate.setDate(checkDate.getDate() - 1);
    }

    // Condition checks
    if (logs.length >= 1) unlock('first-log', 'Langkah Pertama', 'Log pertama apapun');

    if (currentStreak >= 3) unlock('streak-3', '3 Hari Berturut', 'Streak 3 hari');
    if (currentStreak >= 7) unlock('streak-7', 'Seminggu Penuh', 'Streak 7 hari');
    if (currentStreak >= 30) unlock('streak-30', 'Konsisten Sebulan', 'Streak 30 hari');
    if (currentStreak >= 100) unlock('streak-100', 'Dedikasi Total', 'Streak 100 hari');

    if (totalHours >= 10) unlock('total-10h', '10 Jam Immersion', 'Total 10 jam');
    if (totalHours >= 50) unlock('total-50h', '50 Jam Immersion', 'Total 50 jam');
    if (totalHours >= 100) unlock('total-100h', 'Centurion', 'Total 100 jam');
    if (totalHours >= 500) unlock('total-500h', 'Setengah Ribu', 'Total 500 jam');
    if (totalHours >= 1000) unlock('total-1000h', 'Seribu Jam', 'Total 1000 jam');

    if (totalChars >= 10000) unlock('chars-10k', 'Pembaca Pemula', '10,000 karakter dibaca');
    if (totalChars >= 100000) unlock('chars-100k', 'Pembaca Sejati', '100,000 karakter');
    if (totalChars >= 1000000) unlock('chars-1m', 'Devourer', '1,000,000 karakter');

    if (mediaList.filter(m => m.type === 'anime' && m.status === 'completed').length >= 1) {
        unlock('anime-complete', 'Tamat Pertama', 'Selesaikan 1 anime');
    }
    if (completedMediaCount >= 10) unlock('media-10', 'Kuantitas', 'Selesaikan 10 media apapun');

    const categories = new Set(logs.map(l => l.type));
    if (categories.size >= 6) unlock('all-category', 'Omnivorous', 'Punya log di semua 6 kategori');

    const animeLogsUserId = logs.filter(l => l.type === 'anime' && !l.isAutoGenerated);
    if (animeLogsUserId.some(l => l.watchMode === 'raw')) unlock('first-raw', 'Raw Watcher', 'Pertama kali log anime tanpa subtitle');

    // Check "No Sub November" type logic - rough logic: all anime logs this month are raw and count >= 5
    const thisMonth = pd(new Date()).substring(0, 7);
    const thisMonthAnime = animeLogsUserId.filter(l => l.date.startsWith(thisMonth));
    if (thisMonthAnime.length >= 5 && thisMonthAnime.every(l => l.watchMode === 'raw')) {
        unlock('raw-month', 'No Sub Month', 'Semua log anime bulan ini adalah raw');
    }

    // Raw ratio
    if (animeLogsUserId.length > 10) {
        const rawCount = animeLogsUserId.filter(l => l.watchMode === 'raw').length;
        const ratio = rawCount / animeLogsUserId.length;
        if (ratio >= 0.5) unlock('raw-ratio-50', 'Setengah Jalan', 'Raw ratio mencapai 50% all-time');
        if (ratio >= 0.9) unlock('raw-ratio-90', 'Almost Native', 'Raw ratio mencapai 90% all-time');
    }

    // Speed check
    for (const log of logs.filter(l => (l.type === 'ln' || l.type === 'vn') && l.chars > 0 && l.durationMinutes > 0)) {
        const speed = (log.chars / log.durationMinutes) * 60;
        if (speed >= 500 && log.durationMinutes >= 15) {
            unlock('speed-500', 'Kecepatan Cahaya', 'Reading speed 500+ chars/jam dalam satu sesi');
            break;
        }
    }
}

export function calculateLevel(totalHours) {
    if (totalHours < 10) return { level: 1, name: 'Pemula', next: 10, progress: (totalHours / 10) * 100 };
    if (totalHours < 50) return { level: 2, name: 'Penjelajah', next: 50, progress: ((totalHours - 10) / 40) * 100 };
    if (totalHours < 100) return { level: 3, name: 'Pelajar', next: 100, progress: ((totalHours - 50) / 50) * 100 };
    if (totalHours < 300) return { level: 4, name: 'Enthusiast', next: 300, progress: ((totalHours - 100) / 200) * 100 };
    if (totalHours < 500) return { level: 5, name: 'Dedicated', next: 500, progress: ((totalHours - 300) / 200) * 100 };
    if (totalHours < 1000) return { level: 6, name: 'Advanced', next: 1000, progress: ((totalHours - 500) / 500) * 100 };
    if (totalHours < 2000) return { level: 7, name: 'Expert', next: 2000, progress: ((totalHours - 1000) / 1000) * 100 };
    if (totalHours < 5000) return { level: 8, name: 'Master', next: 5000, progress: ((totalHours - 2000) / 3000) * 100 };
    return { level: 9, name: 'Legend', next: totalHours, progress: 100 };
}
