import { defineComponent, ref, onMounted, computed, inject } from 'https://unpkg.com/vue@3/dist/vue.esm-browser.js';
import { getLogsAll, getMediaAll, getAchievements } from '../db.js';
import { getTodayDateString, estimateCompletion, formatDuration, formatChars, convertToHours } from '../utils.js';
import Heatmap from '../components/Heatmap.js';
import MediaCard from '../components/MediaCard.js';
import { calculateLevel } from '../gamification.js';

export default defineComponent({
    name: 'Dashboard',
    components: { Heatmap, MediaCard },
    setup() {
        const isLoading = ref(true);
        const todayStr = getTodayDateString();

        // Summary
        const todayMinutes = ref(0);
        const todayCategories = ref({});

        // Streak
        const streak = ref(0);
        const longestStreak = ref(0);
        const daysThisMonth = ref(0);
        const totalDaysMonth = new Date(new Date().getFullYear(), new Date().getMonth() + 1, 0).getDate();

        // Level
        const levelInfo = ref({});

        // Quick Stats
        const allTimeHours = ref(0);
        const monthHours = ref(0);
        const totalChars = ref(0);
        const totalEps = ref(0);

        const heatmapData = ref([]);
        const recentLogs = ref([]);
        const activeMedia = ref([]);

        const typeIcons = {
            anime: '📺', manga: '📖', ln: '📚', vn: '🎮', podcast: '🎧', anki: '📇'
        };

        const loadData = async () => {
            isLoading.value = true;
            try {
                const allLogs = await getLogsAll();
                const allMedia = await getMediaAll();

                // Global Totals
                let totalMin = 0;
                let monthMin = 0;
                let chars = 0;
                let eps = 0;

                const monthPrefix = todayStr.substring(0, 7);
                const activeDatesThisMonth = new Set();
                const allActiveDates = new Set();

                // Prepare heatmap
                const hmap = new Map();

                allLogs.forEach(log => {
                    if (log.isAutoGenerated) return;

                    const min = Number(log.durationMinutes) || 0;
                    totalMin += min;

                    if (log.date === todayStr) {
                        todayMinutes.value += min;
                        todayCategories.value[log.type] = (todayCategories.value[log.type] || 0) + min;
                    }

                    if (log.date.startsWith(monthPrefix)) {
                        monthMin += min;
                        activeDatesThisMonth.add(log.date);
                    }

                    if (log.chars) chars += Number(log.chars);
                    if (log.type === 'anime' && log.episodes) eps += Number(log.episodes);

                    allActiveDates.add(log.date);

                    // Heatmap counting
                    const c = hmap.get(log.date) || 0;
                    hmap.set(log.date, c + min);
                });

                // Fixed: accurately round the hours to 1 decimal instead of truncating
                allTimeHours.value = Math.round((totalMin / 60) * 10) / 10;
                monthHours.value = Math.round((monthMin / 60) * 10) / 10;
                totalChars.value = chars;
                totalEps.value = eps;
                daysThisMonth.value = activeDatesThisMonth.size;

                levelInfo.value = calculateLevel(totalMin / 60);

                const hData = [];
                hmap.forEach((val, key) => hData.push({ date: key, minutes: val }));
                heatmapData.value = hData;

                // Streaks
                const sortedDates = [...allActiveDates].sort().reverse();
                let cs = 0;
                let ls = 0;
                let tempCs = 0;

                const pd = (d) => {
                    const p = n => n.toString().padStart(2, '0');
                    return `${d.getFullYear()}-${p(d.getMonth() + 1)}-${p(d.getDate())}`;
                };

                let checkDate = new Date();
                if (!sortedDates.includes(pd(checkDate))) {
                    checkDate.setDate(checkDate.getDate() - 1);
                }

                while (sortedDates.includes(pd(checkDate))) {
                    cs++;
                    checkDate.setDate(checkDate.getDate() - 1);
                }
                streak.value = cs;

                // Longest Streak (Fixed to properly calculate days using reliable date math)
                if (sortedDates.length > 0) {
                    let currentTemp = 1;
                    longestStreak.value = 1;
                    for (let i = 0; i < sortedDates.length - 1; i++) {
                        const [y1, m1, day1] = sortedDates[i].split('-').map(Number);
                        const [y2, m2, day2] = sortedDates[i + 1].split('-').map(Number);

                        const date1 = new Date(y1, m1 - 1, day1);
                        const date2 = new Date(y2, m2 - 1, day2);
                        const diffTime = Math.abs(date1 - date2);
                        const diffDays = Math.round(diffTime / (1000 * 60 * 60 * 24));

                        if (diffDays === 1) {
                            currentTemp++;
                        } else {
                            if (currentTemp > longestStreak.value) longestStreak.value = currentTemp;
                            currentTemp = 1;
                        }
                    }
                    if (currentTemp > longestStreak.value) longestStreak.value = currentTemp;
                }

                // Active Media
                const mediaTimeMap = new Map();
                const mediaRecentLogsMap = new Map();

                const sevenDaysAgo = new Date();
                sevenDaysAgo.setDate(sevenDaysAgo.getDate() - 7);
                const limitDate = pd(sevenDaysAgo);

                allLogs.forEach(log => {
                    if (log.isAutoGenerated) return;
                    if (log.mediaId) {
                        const currentTotal = mediaTimeMap.get(log.mediaId) || 0;
                        mediaTimeMap.set(log.mediaId, currentTotal + log.durationMinutes);

                        if (log.date >= limitDate) {
                            const rlist = mediaRecentLogsMap.get(log.mediaId) || [];
                            rlist.push(log);
                            mediaRecentLogsMap.set(log.mediaId, rlist);
                        }
                    }
                });

                activeMedia.value = allMedia
                    .filter(m => m.status === 'watching')
                    .map(m => {
                        const recent = mediaRecentLogsMap.get(m.id) || [];
                        return {
                            ...m,
                            totalMinutes: mediaTimeMap.get(m.id) || 0,
                            lastUpdate: recent.length ? Math.max(...recent.map(r => r.createdAt)) : m.createdAt,
                            estimatedCompletion: estimateCompletion(m, recent)
                        };
                    })
                    .sort((a, b) => b.lastUpdate - a.lastUpdate)
                    .slice(0, 3);

                recentLogs.value = allLogs.filter(l => !l.isAutoGenerated).sort((a, b) => b.createdAt - a.createdAt).slice(0, 5);

            } catch (e) {
                console.error(e);
            } finally {
                isLoading.value = false;
            }
        };

        onMounted(loadData);

        return {
            isLoading, todayMinutes, todayCategories, streak, longestStreak, daysThisMonth, totalDaysMonth,
            allTimeHours, monthHours, totalChars, totalEps, heatmapData, recentLogs, activeMedia, formatDuration, formatChars,
            typeIcons, levelInfo
        };
    },
    template: `
    <div class="max-w-6xl mx-auto space-y-8 animate-fade-in pb-12">
        <div class="flex flex-col md:flex-row gap-6 items-stretch">
            
            <div class="flex-1 bg-indigo-600 dark:bg-indigo-900 rounded-2xl p-6 md:p-8 shadow-md text-white overflow-hidden relative group">
                <div class="absolute -right-8 -top-8 w-40 h-40 bg-white/10 rounded-full blur-3xl group-hover:bg-white/20 transition-all duration-700"></div>
                <div class="absolute -left-8 -bottom-8 w-32 h-32 bg-black/10 rounded-full blur-2xl"></div>
                
                <div class="relative z-10">
                    <h2 class="text-3xl font-bold mb-2 tracking-tight">Level {{ levelInfo.level || 1 }}: {{ levelInfo.name || 'Pemula' }}</h2>
                    <p class="text-indigo-200 text-sm font-medium mb-6 animate-pulse">Hari yang bagus untuk immersion!</p>
                    
                    <div class="w-full bg-black/20 rounded-full h-2 mb-2 overflow-hidden shadow-inner backdrop-blur-sm border border-white/5">
                        <div class="bg-gradient-to-r from-yellow-300 to-yellow-500 h-2 rounded-full shadow-[0_0_10px_rgba(234,179,8,0.5)] transition-all duration-1000 ease-out" :style="{ width: (levelInfo.progress || 0) + '%' }"></div>
                    </div>
                    <div class="flex justify-between text-xs font-semibold text-indigo-200 uppercase tracking-widest">
                        <span>{{ allTimeHours }} Jam</span>
                        <span>{{ levelInfo.next }} Jam s/d Lvl {{ (levelInfo.level || 1) + 1 }}</span>
                    </div>
                </div>
            </div>
            
            <div class="w-full md:w-80 bg-white dark:bg-gray-800 rounded-2xl p-6 shadow-sm border border-gray-100 dark:border-gray-700 flex flex-col justify-between hover:shadow-md transition-shadow">
                <div class="flex justify-between items-start mb-4">
                    <h3 class="font-bold text-gray-800 dark:text-gray-200 uppercase tracking-widest text-xs">Hari Ini</h3>
                    <div class="bg-indigo-50 dark:bg-indigo-900/40 text-indigo-600 dark:text-indigo-400 p-2 rounded-lg">
                       <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
                    </div>
                </div>
                <div>
                     <div class="text-4xl font-light text-gray-900 dark:text-white tabular-nums tracking-tighter">{{ formatDuration(todayMinutes) }}</div>
                     
                     <div class="mt-4 flex flex-wrap gap-2">
                         <span v-if="Object.keys(todayCategories).length === 0" class="text-xs text-gray-400">Belum ada aktivitas</span>
                         <span v-for="(mins, cat) in todayCategories" :key="cat" class="px-2 py-1 bg-gray-50 dark:bg-gray-900 border border-gray-100 dark:border-gray-700 rounded-md text-xs font-semibold text-gray-600 dark:text-gray-300 flex items-center gap-1 shadow-sm">
                             {{ typeIcons[cat] }} {{ formatDuration(mins) }}
                         </span>
                     </div>
                </div>
            </div>
        </div>

        <div class="grid grid-cols-1 lg:grid-cols-3 gap-6">
            
            <div class="bg-white dark:bg-gray-800 rounded-2xl p-6 shadow-sm border border-gray-100 dark:border-gray-700 flex flex-col justify-between hover:border-orange-200 dark:hover:border-orange-900/50 transition-colors group">
                <div>
                    <div class="flex items-center justify-between mb-4 text-orange-500">
                        <svg class="w-6 h-6 animate-pulse" fill="currentColor" viewBox="0 0 20 20"><path fill-rule="evenodd" d="M12.395 2.553a1 1 0 00-1.45-.385c-.345.23-.614.558-.822.88-.214.33-.403.713-.57 1.116-.334.804-.614 1.768-.84 2.734a31.365 31.365 0 00-.613 3.58 2.64 2.64 0 01-.945-1.067c-.328-.68-.398-1.534-.398-2.654A1 1 0 005.05 6.05 6.981 6.981 0 003 11a7 7 0 1011.95-4.95c-.592-.591-.98-.985-1.348-1.467-.363-.476-.724-1.063-1.207-2.03zM12.12 15.12A3 3 0 017 13s.879.5 2.5.5c0-1 .5-4 1.25-4.5.5 1 .786 1.293 1.371 1.879A2.99 2.99 0 0113 13a2.99 2.99 0 01-.879 2.121z" clip-rule="evenodd"></path></svg>
                        <span class="text-xs font-bold uppercase tracking-widest text-gray-500 dark:text-gray-400 group-hover:text-orange-500 transition-colors">Hot Streak</span>
                    </div>
                    <div class="flex items-baseline gap-2 mb-1">
                        <span class="text-5xl font-light text-gray-900 dark:text-white tracking-tighter">{{ streak }}</span>
                        <span class="text-gray-500 dark:text-gray-400 font-medium">hari</span>
                    </div>
                    <p class="text-xs text-gray-500 dark:text-gray-400 border-b border-gray-100 dark:border-gray-700 pb-4 mb-4">Terpanjang: <span class="font-bold text-gray-900 dark:text-white">{{ longestStreak }} hari</span></p>
                </div>
                
                <div class="flex items-center justify-between text-sm">
                    <span class="text-gray-600 dark:text-gray-300 font-medium tracking-tight">Bulan ini</span>
                    <span class="font-bold px-2.5 py-1 bg-green-50 dark:bg-green-900/30 text-green-700 dark:text-green-400 rounded-lg whitespace-nowrap"><span class="tabular-nums">{{ daysThisMonth }}</span> / {{ totalDaysMonth }} hari</span>
                </div>
            </div>

            <div class="lg:col-span-2 bg-white dark:bg-gray-800 rounded-2xl p-6 shadow-sm border border-gray-100 dark:border-gray-700">
                <h3 class="font-bold text-gray-800 dark:text-gray-200 uppercase tracking-widest text-xs mb-4 text-center sm:text-left">Aktivitas Tahunan</h3>
                <div class="flex justify-center sm:justify-start">
                     <Heatmap :data="heatmapData" :year="new Date().getFullYear()" />
                </div>
            </div>
        </div>

        <div class="grid grid-cols-2 md:grid-cols-4 gap-4">
            <div class="bg-white dark:bg-gray-800 p-5 rounded-2xl shadow-sm border border-gray-100 dark:border-gray-750 flex flex-col justify-center items-center text-center transform hover:scale-[1.02] transition-transform">
                <div class="w-10 h-10 rounded-full bg-blue-50 dark:bg-blue-900/30 flex items-center justify-center text-blue-500 mb-3"><svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg></div>
                <div class="text-2xl font-light text-gray-900 dark:text-white tabular-nums tracking-tighter">{{ allTimeHours }}</div>
                <div class="text-[10px] font-bold text-gray-400 uppercase tracking-widest mt-1">Total Jam</div>
            </div>
            
            <div class="bg-white dark:bg-gray-800 p-5 rounded-2xl shadow-sm border border-gray-100 dark:border-gray-750 flex flex-col justify-center items-center text-center transform hover:scale-[1.02] transition-transform">
                <div class="w-10 h-10 rounded-full bg-emerald-50 dark:bg-emerald-900/30 flex items-center justify-center text-emerald-500 mb-3"><svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z"></path></svg></div>
                <div class="text-2xl font-light text-gray-900 dark:text-white tabular-nums tracking-tighter">{{ monthHours }}</div>
                <div class="text-[10px] font-bold text-gray-400 uppercase tracking-widest mt-1">Jam Bulan Ini</div>
            </div>
            
            <div class="bg-white dark:bg-gray-800 p-5 rounded-2xl shadow-sm border border-gray-100 dark:border-gray-750 flex flex-col justify-center items-center text-center transform hover:scale-[1.02] transition-transform">
                <div class="w-10 h-10 rounded-full bg-amber-50 dark:bg-amber-900/30 flex items-center justify-center text-amber-500 mb-3"><svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 5h12M9 3v2m1.048 9.5A18.022 18.022 0 016.412 9m6.088 9h7M11 21l5-10 5 10M12.751 5C11.783 10.77 8.07 15.61 3 18.129"></path></svg></div>
                <div class="text-xl md:text-2xl font-light text-gray-900 dark:text-white tracking-tighter truncate w-full">{{ formatChars(totalChars) }}</div>
                <div class="text-[10px] font-bold text-gray-400 uppercase tracking-widest mt-1">Karakter</div>
            </div>
            
            <div class="bg-white dark:bg-gray-800 p-5 rounded-2xl shadow-sm border border-gray-100 dark:border-gray-750 flex flex-col justify-center items-center text-center transform hover:scale-[1.02] transition-transform">
                <div class="w-10 h-10 rounded-full bg-purple-50 dark:bg-purple-900/30 flex items-center justify-center text-purple-500 mb-3"><svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 4v16M17 4v16M3 8h4m10 0h4M3 12h18M3 16h4m10 0h4M4 20h16a1 1 0 001-1V5a1 1 0 00-1-1H4a1 1 0 00-1 1v14a1 1 0 001 1z"></path></svg></div>
                <div class="text-2xl font-light text-gray-900 dark:text-white tabular-nums tracking-tighter">{{ formatChars(totalEps) }}</div>
                <div class="text-[10px] font-bold text-gray-400 uppercase tracking-widest mt-1">Episode</div>
            </div>
        </div>

        <div class="grid grid-cols-1 lg:grid-cols-2 gap-8">
            
            <div class="space-y-4">
                <div class="flex justify-between items-center mb-1">
                    <h3 class="font-bold text-gray-900 dark:text-white flex items-center gap-2">
                        <span class="w-2 h-2 rounded-full bg-indigo-500"></span>
                        Sedang Aktif
                    </h3>
                    <a href="#/library" class="text-sm font-bold text-indigo-600 dark:text-indigo-400 hover:text-indigo-500 uppercase tracking-wider">Top 3</a>
                </div>
                
                <div v-if="activeMedia.length === 0" class="bg-white dark:bg-gray-800 rounded-2xl p-8 text-center border border-gray-100 dark:border-gray-750 border-dashed">
                    <p class="text-gray-500 dark:text-gray-400 text-sm">Tidak ada media yang sedang diikuti.</p>
                </div>
                
                <div v-for="media in activeMedia" :key="media.id" class="h-[140px] shadow-sm">
                    <MediaCard :media="media" :totalMinutes="media.totalMinutes" :estimatedCompletion="media.estimatedCompletion" @click="window.location.hash = '#/library'" />
                </div>
            </div>

            <div class="space-y-4">
                <div class="flex justify-between items-center mb-1">
                    <h3 class="font-bold text-gray-900 dark:text-white flex items-center gap-2">
                        <span class="w-2 h-2 rounded-full bg-orange-500"></span>
                        Aktivitas Terakhir
                    </h3>
                    <a href="#/log" class="text-sm font-bold text-indigo-600 dark:text-indigo-400 hover:text-indigo-500 uppercase tracking-wider">Semua Log</a>
                </div>
                
                <div v-if="recentLogs.length === 0" class="bg-white dark:bg-gray-800 rounded-2xl p-8 text-center border border-gray-100 dark:border-gray-750 border-dashed">
                    <p class="text-gray-500 dark:text-gray-400 text-sm">Belum ada log tercatat.</p>
                </div>
                
                <div class="space-y-3">
                    <div v-for="log in recentLogs" :key="log.id" class="flex gap-4 items-center bg-white dark:bg-gray-800 p-4 rounded-xl shadow-sm border border-gray-100 dark:border-gray-750 hover:border-gray-300 dark:hover:border-gray-600 transition-colors cursor-default">
                         <div class="w-10 h-10 rounded-full bg-gray-50 dark:bg-gray-700/50 flex items-center justify-center text-lg border border-gray-100 dark:border-gray-600 shadow-inner">
                              {{ typeIcons[log.type] }}
                         </div>
                         <div class="flex-1 min-w-0">
                             <div class="flex justify-between items-baseline mb-0.5">
                                 <h4 class="font-bold text-gray-900 dark:text-white truncate text-sm" :title="log.mediaTitle">{{ log.mediaTitle }}</h4>
                                 <span class="text-[10px] text-gray-400 uppercase tracking-wider shrink-0 ml-2 font-bold">{{ log.date === todayStr ? 'HARI INI' : log.date }}</span>
                             </div>
                             <p class="text-xs text-gray-500 dark:text-gray-400 flex items-center gap-1.5 flex-wrap">
                                 <span class="font-bold text-indigo-600 dark:text-indigo-400">{{ formatDuration(log.durationMinutes) }}</span>
                                 <span>•</span>
                                 <span class="uppercase tracking-wider font-semibold opacity-70">{{ log.type }}</span>
                                 <span v-if="log.episodes || log.pages || log.chars">
                                     • {{ log.episodes ? log.episodes + ' Ep' : log.pages ? log.pages + ' Hal' : log.chars + ' Chr' }}
                                 </span>
                             </p>
                         </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
  `
});