import { defineComponent, ref, computed, onMounted, inject, watch } from 'https://unpkg.com/vue@3/dist/vue.esm-browser.js';
import MediaCard from '../components/MediaCard.js';
import { getMediaAll, saveMedia, deleteMedia, getLogsAll } from '../db.js';
import { searchAniList, importAniListUser } from '../api/anilist.js';
import { searchVNDB } from '../api/vndb.js';
import { searchGoogleBooks } from '../api/googlebooks.js';
import { generateUUID, estimateCompletion, getTodayDateString } from '../utils.js';

export default defineComponent({
    name: 'Library',
    components: { MediaCard },
    setup() {
        const showToast = inject('showToast');
        const isLoading = ref(true);
        const mediaList = ref([]);
        const logsList = ref([]);

        // Filters
        const searchQuery = ref('');
        const filterType = ref('');
        const filterStatus = ref('');
        const sortBy = ref('updatedAt');

        const showAddModal = ref(false);
        const apiLoading = ref(false);
        const searchApiQuery = ref('');
        const searchApiResults = ref([]);

        const editModalMedia = ref(null);
        const editForm = ref({});

        const addForm = ref({
            title: '',
            titleJP: '',
            type: 'anime',
            status: 'watching',
            coverUrl: '',
            totalUnits: null,
            currentUnit: 0,
            episodeDuration: 24, // specifically for anime
            anilistId: null,
            vndbId: null
        });

        const loadData = async () => {
            isLoading.value = true;
            try {
                mediaList.value = await getMediaAll();
                logsList.value = await getLogsAll();
            } catch (e) {
                console.error(e);
            } finally {
                isLoading.value = false;
            }
        };

        onMounted(loadData);

        // Calc aggregated data for each media
        const mediaWithStats = computed(() => {
            const timeMap = new Map();
            const logsMap = new Map();

            logsList.value.forEach(log => {
                if (log.isAutoGenerated) return;
                if (log.mediaId) {
                    timeMap.set(log.mediaId, (timeMap.get(log.mediaId) || 0) + log.durationMinutes);

                    const mlogs = logsMap.get(log.mediaId) || [];
                    mlogs.push(log);
                    logsMap.set(log.mediaId, mlogs);
                }
            });

            const sevenDaysAgoStr = new Date(Date.now() - 7 * 86400000).toISOString().split('T')[0];

            return mediaList.value.map(m => {
                const logs = logsMap.get(m.id) || [];
                const recentLogs = logs.filter(l => l.date >= sevenDaysAgoStr);
                const lastUpdate = logs.length > 0 ? Math.max(...logs.map(l => l.createdAt)) : m.createdAt;

                return {
                    ...m,
                    totalMinutes: timeMap.get(m.id) || 0,
                    lastUpdate,
                    estimatedCompletion: estimateCompletion(m, recentLogs)
                };
            });
        });

        const filteredMedia = computed(() => {
            let result = mediaWithStats.value.filter(m =>
                ['anime', 'manga', 'ln', 'vn'].includes(m.type)
            );

            if (searchQuery.value) {
                const q = searchQuery.value.toLowerCase();
                result = result.filter(m => m.title.toLowerCase().includes(q) || (m.titleJP && m.titleJP.toLowerCase().includes(q)));
            }
            if (filterType.value) {
                result = result.filter(m => m.type === filterType.value);
            }
            if (filterStatus.value) {
                result = result.filter(m => m.status === filterStatus.value);
            }

            result.sort((a, b) => {
                if (sortBy.value === 'updatedAt') return b.lastUpdate - a.lastUpdate;
                if (sortBy.value === 'title') return a.title.localeCompare(b.title);
                if (sortBy.value === 'progress') {
                    const percA = a.totalUnits ? a.currentUnit / a.totalUnits : 0;
                    const percB = b.totalUnits ? b.currentUnit / b.totalUnits : 0;
                    return percB - percA;
                }
                if (sortBy.value === 'time') return b.totalMinutes - a.totalMinutes;
                return 0;
            });

            return result;
        });

        // API Search Search logic using debounce
        let searchTimeout = null;
        watch(() => searchApiQuery.value, (newQ) => {
            if (!newQ || newQ.length < 3) {
                searchApiResults.value = [];
                return;
            }
            if (searchTimeout) clearTimeout(searchTimeout);
            searchTimeout = setTimeout(async () => {
                apiLoading.value = true;
                try {
                    // Cache logic could be added here
                    if (addForm.value.type === 'vn') {
                        const res = await searchVNDB(newQ);
                        searchApiResults.value = res.map(r => ({
                            id: r.id,
                            title: r.title,
                            titleJP: r.titles?.find(t => t.lang === 'ja')?.title || '',
                            cover: r.image?.url || '',
                            totalUnits: null
                        }));
                    } else if (addForm.value.type === 'ln') {
                        const res = await searchGoogleBooks(newQ);
                        searchApiResults.value = res.map(r => ({
                            id: r.id,
                            title: r.title,
                            titleJP: r.titleJP,
                            cover: r.cover,
                            totalUnits: null // Volumes are individual search results now
                        }));
                    } else {
                        const typeQuery = addForm.value.type === 'anime' ? 'ANIME' : 'MANGA';
                        const formatQuery = addForm.value.type === 'ln' ? 'NOVEL' : null;
                        const res = await searchAniList(newQ, typeQuery, formatQuery);
                        searchApiResults.value = res.map(r => ({
                            id: r.id,
                            title: r.title.romaji || r.title.english,
                            titleJP: r.title.native || '',
                            cover: r.coverImage?.medium || '',
                            totalUnits: r.episodes || r.chapters || r.volumes || (r.nextAiringEpisode ? r.nextAiringEpisode.episode - 1 : null)
                        }));
                    }
                } catch (e) {
                    showToast('API search gagal', 'error');
                } finally {
                    apiLoading.value = false;
                }
            }, 500);
        });

        const selectApiResult = (res) => {
            addForm.value.title = res.title;
            addForm.value.titleJP = res.titleJP;
            addForm.value.coverUrl = res.cover;
            addForm.value.totalUnits = res.totalUnits;
            if (addForm.value.type === 'vn') {
                addForm.value.vndbId = res.id;
            } else {
                addForm.value.anilistId = res.id;
            }
            searchApiResults.value = [];
            searchApiQuery.value = ''; // clear search box
        };

        const saveNewMedia = async () => {
            if (!addForm.value.title) {
                showToast('Judul wajib diisi', 'error');
                return;
            }

            const newObj = {
                id: generateUUID(),
                createdAt: Date.now(),
                startDate: addForm.value.status === 'watching' ? getTodayDateString() : null,
                ...addForm.value
            };

            try {
                await saveMedia(newObj);
                showToast('Media ditambahkan', 'success');
                showAddModal.value = false;
                loadData();
            } catch (e) {
                showToast('Gagal menyimpan referensi', 'error');
            }
        };

        const openEditModal = (media) => {
            editModalMedia.value = media;
            editForm.value = { ...media };
        };

        const saveEditMedia = async () => {
            try {
                // handle start/end dates
                if (editForm.value.status === 'completed' && editModalMedia.value.status !== 'completed') {
                    if (!editForm.value.endDate) editForm.value.endDate = getTodayDateString();
                }
                if (editForm.value.status === 'watching' && editModalMedia.value.status !== 'watching') {
                    if (!editForm.value.startDate) editForm.value.startDate = getTodayDateString();
                }

                // Clean computed properties before saving to database
                const cleanData = { ...editForm.value };
                delete cleanData.totalMinutes;
                delete cleanData.lastUpdate;
                delete cleanData.estimatedCompletion;

                await saveMedia(cleanData);
                showToast('Media diperbarui', 'success');
                editModalMedia.value = null;
                loadData();
            } catch (e) {
                showToast('Gagal update', 'error');
            }
        };

        const deleteMediaHandler = async (id) => {
            if (!confirm('Hapus media ini? Log sesi yang terkait TIDAK akan ikut dihapus, tapi akan terputus.')) return;
            try {
                await deleteMedia(id);
                showToast('Media dihapus', 'success');
                editModalMedia.value = null;
                loadData();
            } catch (e) {
                showToast('Gagal menghapus', 'error');
            }
        };

        // reset form when opening
        watch(() => showAddModal.value, (val) => {
            if (val) {
                document.body.classList.add('overflow-hidden');
                searchApiQuery.value = '';
                searchApiResults.value = [];
                addForm.value = { title: '', titleJP: '', type: 'anime', status: 'watching', coverUrl: '', totalUnits: null, currentUnit: 0, episodeDuration: 24, anilistId: null, vndbId: null };
            } else {
                document.body.classList.remove('overflow-hidden');
            }
        });

        watch(() => editModalMedia.value, (val) => {
            if (val) {
                document.body.classList.add('overflow-hidden');
            } else {
                document.body.classList.remove('overflow-hidden');
            }
        });

        // clear api results on type change
        watch(() => addForm.value.type, () => {
            searchApiQuery.value = '';
            searchApiResults.value = [];
        });

        return {
            isLoading, filteredMedia, searchQuery, filterType, filterStatus, sortBy,
            showAddModal, apiLoading, searchApiQuery, searchApiResults, addForm, selectApiResult, saveNewMedia,
            editModalMedia, editForm, openEditModal, saveEditMedia, deleteMediaHandler
        };
    },
    template: `
    <div class="relative">
        <div class="max-w-7xl mx-auto space-y-6 pb-12 animate-fade-in">
            
            <div class="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 border-b border-gray-200 dark:border-gray-800 pb-5">
                <div>
                    <h2 class="text-3xl font-bold tracking-tight text-gray-900 dark:text-white">Media Library</h2>
                    <p class="text-gray-500 dark:text-gray-400 text-sm mt-1">Koleksi konten bahasa Jepang-mu.</p>
                </div>
                
                <button @click="showAddModal = true" class="w-full md:w-auto px-6 py-2.5 bg-indigo-600 hover:bg-indigo-500 text-white font-bold rounded-xl transition-all shadow-sm flex items-center justify-center gap-2">
                    <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4"></path></svg>
                    Tambah Media
                </button>
            </div>

            <div class="bg-white dark:bg-gray-800 p-4 rounded-xl shadow-sm border border-gray-100 dark:border-gray-750 flex flex-wrap gap-4 items-center">
                <div class="flex-1 min-w-[200px] relative text-gray-400 focus-within:text-indigo-500">
                    <input type="text" v-model="searchQuery" placeholder="Cari judul..." class="w-full bg-gray-50 dark:bg-gray-900 border border-gray-200 dark:border-gray-700 text-gray-900 dark:text-white rounded-lg pl-10 pr-4 py-2 text-sm outline-none focus:ring-2 focus:ring-indigo-500 transition-shadow">
                    <svg class="w-5 h-5 absolute left-3 top-2" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path></svg>
                </div>
                
                <select v-model="filterType" class="bg-gray-50 dark:bg-gray-900 border border-gray-200 dark:border-gray-700 text-gray-900 dark:text-white rounded-lg px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-indigo-500">
                    <option value="">Semua Kategori</option>
                    <option value="anime">Anime</option>
                    <option value="manga">Manga</option>
                    <option value="ln">Light Novel</option>
                    <option value="vn">Visual Novel</option>
                </select>
                
                <select v-model="filterStatus" class="bg-gray-50 dark:bg-gray-900 border border-gray-200 dark:border-gray-700 text-gray-900 dark:text-white rounded-lg px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-indigo-500">
                    <option value="">Semua Status</option>
                    <option value="watching">Aktif (Watching/Reading)</option>
                    <option value="completed">Selesai</option>
                    <option value="paused">Jeda</option>
                    <option value="dropped">Drop</option>
                    <option value="backlog">Backlog</option>
                </select>

                <select v-model="sortBy" class="bg-gray-50 dark:bg-gray-900 border border-gray-200 dark:border-gray-700 text-gray-900 dark:text-white rounded-lg px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-indigo-500">
                    <option value="updatedAt">Terakhir Update</option>
                    <option value="title">Judul (A-Z)</option>
                    <option value="progress">Persentase Selesai</option>
                    <option value="time">Jam Terbanyak</option>
                </select>
            </div>

            <div v-if="isLoading" class="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 gap-6">
                <div v-for="i in 5" :key="i" class="h-64 bg-white dark:bg-gray-800 rounded-2xl animate-pulse"></div>
            </div>
            
            <div v-else-if="filteredMedia.length === 0" class="py-20 text-center flex flex-col items-center">
                <div class="w-24 h-24 mb-6 bg-gray-100 dark:bg-gray-800 rounded-full flex items-center justify-center text-gray-300 dark:text-gray-600">
                    <svg class="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 002-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10"></path></svg>
                </div>
                <h3 class="text-xl font-bold text-gray-900 dark:text-white mb-2">Belum ada media</h3>
                <p class="text-gray-500 dark:text-gray-400 max-w-sm mx-auto">Tambahkan anime, manga, atau konten lainnya untuk mulai tracking.</p>
            </div>

            <div v-else class="grid grid-cols-2 lg:grid-cols-4 xl:grid-cols-5 gap-4 md:gap-6">
                <MediaCard 
                    v-for="media in filteredMedia" 
                    :key="media.id" 
                    :media="media" 
                    :totalMinutes="media.totalMinutes"
                    :estimatedCompletion="media.estimatedCompletion"
                    @click="openEditModal(media)" 
                />
            </div>
        </div>

        <!-- Add Modal -->
        <transition name="fade">
        <div v-if="showAddModal" class="fixed inset-0 z-[150] flex items-center justify-center p-4">
            <!-- Backdrop with Blur -->
            <div class="absolute inset-0 bg-black/60 backdrop-blur-md" @click="showAddModal = false"></div>
            
            <div class="bg-white dark:bg-gray-800 rounded-3xl shadow-2xl w-full max-w-xl relative z-20 flex flex-col max-h-[90vh] ring-1 ring-white/10 animate-scale-in">
                <div class="px-8 py-5 border-b border-gray-100 dark:border-gray-700 flex justify-between items-center bg-gray-50/50 dark:bg-gray-800/50">
                    <h3 class="font-bold text-lg dark:text-white flex items-center gap-2">
                        <span class="w-2 h-2 rounded-full bg-indigo-500"></span> Tambah Media Baru
                    </h3>
                    <button @click="showAddModal = false" class="text-gray-400 hover:text-gray-700 dark:hover:text-white transition-colors p-2 rounded-full hover:bg-gray-200 dark:hover:bg-gray-700">
                        <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path></svg>
                    </button>
                </div>

                <div class="p-8 overflow-y-auto custom-scrollbar space-y-6 flex-1">
                    <!-- Type Selection -->
                    <div>
                        <label class="block text-[11px] font-bold text-gray-500 dark:text-gray-400 uppercase tracking-widest mb-3">Tipe Konten</label>
                        <div class="flex flex-wrap gap-2">
                           <label v-for="t in ['anime','manga','ln','vn']" :key="t" class="cursor-pointer">
                               <input type="radio" v-model="addForm.type" :value="t" class="hidden">
                               <span class="px-4 py-2 border rounded-full text-xs font-bold uppercase transition-all" :class="addForm.type === t ? 'border-indigo-500 bg-indigo-500 text-white shadow-md' : 'border-gray-200 dark:border-gray-700 text-gray-600 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-700'">{{ t === 'ln' ? 'Light Novel' : t === 'vn' ? 'Visual Novel' : t }}</span>
                           </label>
                        </div>
                    </div>

                    <!-- Search API -->
                    <div v-if="['anime','manga','vn','ln'].includes(addForm.type)" class="bg-indigo-50/50 dark:bg-indigo-900/20 p-5 rounded-2xl border border-indigo-100 dark:border-indigo-800/30">
                        <label class="block text-[11px] font-bold text-indigo-800 dark:text-indigo-300 uppercase tracking-widest mb-1.5 flex justify-between">
                            <span>Auto-fill dari Database</span>
                            <span class="text-[10px]">{{ addForm.type === 'vn' ? 'Via VNDB' : 'Via AniList' }}</span>
                        </label>
                        <div class="relative">
                            <input type="text" v-model="searchApiQuery" placeholder="Ketik minimal 3 huruf..." autocomplete="off" class="w-full bg-white dark:bg-gray-900 border border-indigo-200 dark:border-indigo-700/50 rounded-xl px-4 py-3 text-sm dark:text-white focus:ring-2 focus:ring-indigo-500 outline-none shadow-sm placeholder-gray-400">
                            <svg v-if="apiLoading" class="w-5 h-5 absolute right-4 top-3 animate-spin text-indigo-500" fill="none" viewBox="0 0 24 24"><circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle><path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"></path></svg>
                        </div>
                        
                        <!-- Search Results Dropdown -->
                        <div v-if="searchApiResults.length > 0" class="mt-2 bg-white dark:bg-gray-900 border border-indigo-100 dark:border-indigo-700/50 rounded-xl max-h-48 overflow-y-auto custom-scrollbar shadow-lg divide-y divide-gray-100 dark:divide-gray-800 absolute z-50 w-[calc(100%-4rem)] md:w-auto left-8 right-8 md:static shadow-black/5">
                            <div v-for="res in searchApiResults" :key="res.id" @click="selectApiResult(res)" class="p-3 hover:bg-indigo-50 dark:hover:bg-indigo-900/30 cursor-pointer flex gap-3 items-center group transition-colors">
                                <img v-if="res.cover" :src="res.cover" class="w-10 h-14 object-cover rounded border border-gray-100 dark:border-gray-800 group-hover:scale-105 transition-transform" />
                                <div v-else class="w-10 h-14 bg-gray-100 dark:bg-gray-800 rounded group-hover:scale-105 transition-transform"></div>
                                <div class="flex-1 min-w-0">
                                    <div class="text-sm font-bold text-gray-900 dark:text-white truncate">{{ res.title }}</div>
                                    <div class="text-[10px] text-gray-500 dark:text-gray-400 truncate">
                                        {{ res.titleJP }} 
                                        <span v-if="res.totalUnits"> • {{ res.totalUnits }} {{ addForm.type === 'anime' ? 'eps' : addForm.type === 'manga' ? 'ch/vol' : 'unit' }}</span>
                                        <span v-else-if="addForm.type === 'ln' || addForm.type === 'vn'"> • Karakter Based</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- Manual Form Fields -->
                    <div class="space-y-4">
                        <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                            <div>
                                <label class="block text-[11px] font-bold text-gray-500 dark:text-gray-400 uppercase tracking-widest mb-1.5 flex justify-between"><span class="after:content-['*'] after:text-red-500 mt-0.5">Judul</span></label>
                                <input type="text" v-model="addForm.title" required class="w-full bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-700 rounded-lg px-3 py-2.5 text-sm dark:text-white focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 outline-none transition-shadow shadow-sm">
                            </div>
                            <div>
                                <label class="block text-[11px] font-bold text-gray-500 dark:text-gray-400 uppercase tracking-widest mb-1.5">Judul Asli (Kanji/Kana)</label>
                                <input type="text" v-model="addForm.titleJP" class="w-full bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-700 rounded-lg px-3 py-2.5 text-sm dark:text-white focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 outline-none transition-shadow shadow-sm">
                            </div>
                        </div>

                        <div class="grid grid-cols-2 gap-4">
                            <div>
                                <label class="block text-[11px] font-bold text-gray-500 dark:text-gray-400 uppercase tracking-widest mb-1.5">Status</label>
                                <select v-model="addForm.status" class="w-full bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-700 rounded-lg px-3 py-2.5 text-sm dark:text-white focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 outline-none shadow-sm">
                                    <option value="watching">Aktif (Watching/Reading)</option>
                                    <option value="completed">Selesai</option>
                                    <option value="paused">Jeda</option>
                                    <option value="dropped">Drop</option>
                                    <option value="backlog">Backlog</option>
                                </select>
                            </div>
                            <div>
                                <label class="block text-[11px] font-bold text-gray-500 dark:text-gray-400 uppercase tracking-widest mb-1.5 flex items-center justify-between">
                                    <span v-if="addForm.type === 'vn' || addForm.type === 'ln'">Total Karakter (Estimasi)</span>
                                    <span v-else-if="addForm.type === 'anime'">Total Episode</span>
                                    <span v-else-if="addForm.type === 'manga'">Total Chapter</span>
                                    <span v-else>Total Unit</span>
                                </label>
                                <input type="number" v-model.number="addForm.totalUnits" class="w-full bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-700 rounded-lg px-3 py-2.5 text-sm dark:text-white focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 outline-none shadow-sm" placeholder="Kosongkan jika unknown (e.g. 100000)">
                            </div>
                        </div>

                        <div>
                            <label class="block text-[11px] font-bold text-gray-500 dark:text-gray-400 uppercase tracking-widest mb-1.5">URL Cover Image</label>
                            <input type="text" v-model="addForm.coverUrl" class="w-full bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-700 rounded-lg px-3 py-2.5 text-sm dark:text-white focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 outline-none shadow-sm">
                        </div>
                    </div>
                </div>

                <div class="px-8 py-5 border-t border-gray-100 dark:border-gray-700 bg-gray-50/50 dark:bg-gray-800/50 flex justify-end">
                    <button @click="saveNewMedia" class="px-8 py-3 bg-indigo-600 hover:bg-indigo-500 text-white font-bold rounded-xl transition-all hover:shadow-lg focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 dark:focus:ring-offset-gray-800">
                        Simpan
                    </button>
                </div>
            </div>
        </div>
        </transition>

        <!-- Edit Modal -->
        <transition name="fade">
        <div v-if="editModalMedia" class="fixed inset-0 z-[150] flex items-center justify-center p-4">
            <!-- Backdrop with Blur -->
            <div class="absolute inset-0 bg-black/60 backdrop-blur-md" @click="editModalMedia = null"></div>
            
            <div class="bg-white dark:bg-gray-800 rounded-3xl shadow-2xl w-full max-w-md relative z-20 flex flex-col max-h-[90vh] ring-1 ring-white/10 animate-scale-in">
                <div class="px-6 py-5 border-b border-gray-100 dark:border-gray-700 flex justify-between items-center bg-gray-50/50 dark:bg-gray-800/50">
                    <h3 class="font-bold text-lg dark:text-white truncate pr-4 text-center w-full">Edit {{ editModalMedia.title }}</h3>
                    <button @click="editModalMedia = null" class="text-gray-400 p-2 hover:text-gray-600 dark:hover:text-white transition-colors">
                        <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path></svg>
                    </button>
                </div>

                <div class="p-6 overflow-y-auto custom-scrollbar space-y-5 flex-1">
                    <div class="flex flex-col items-center mb-6">
                        <img v-if="editForm.coverUrl" :src="editForm.coverUrl" class="w-24 h-36 object-cover rounded-xl shadow-md border border-gray-100 dark:border-gray-700 mb-4" />
                        <div v-else class="w-24 h-36 bg-gray-100 dark:bg-gray-700 rounded-xl shadow-md mb-4 flex items-center justify-center text-gray-400 border border-gray-200 dark:border-gray-600"><svg class="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z"></path></svg></div>
                    </div>

                    <div>
                        <label class="block text-[11px] font-bold text-gray-500 dark:text-gray-400 uppercase tracking-widest mb-1.5">Judul Utama</label>
                        <input type="text" v-model="editForm.title" class="w-full bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-700 rounded-lg px-3 py-2 text-sm dark:text-white focus:ring-2 focus:ring-indigo-500 mb-4">
                        
                        <label class="block text-[11px] font-bold text-gray-500 dark:text-gray-400 uppercase tracking-widest mb-1.5">Status</label>
                        <select v-model="editForm.status" class="w-full bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-700 rounded-lg px-3 py-2 text-sm dark:text-white focus:ring-2 focus:ring-indigo-500 mb-4">
                            <option value="watching">Aktif (Watching/Reading)</option>
                            <option value="completed">Selesai</option>
                            <option value="paused">Jeda</option>
                            <option value="dropped">Drop</option>
                            <option value="backlog">Backlog</option>
                        </select>
                        
                        <div class="grid grid-cols-2 gap-4 mb-4">
                            <div>
                                <label class="block text-[11px] font-bold text-gray-500 dark:text-gray-400 uppercase tracking-widest mb-1.5">Progress Unit</label>
                                <input type="number" v-model.number="editForm.currentUnit" class="w-full bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-700 rounded-lg px-3 py-2 text-sm dark:text-white focus:ring-2 focus:ring-indigo-500">
                            </div>
                            <div>
                                <label class="block text-[11px] font-bold text-gray-500 dark:text-gray-400 uppercase tracking-widest mb-1.5">
                                    {{ (editModalMedia.type === 'vn' || editModalMedia.type === 'ln') ? 'Total Karakter' : editModalMedia.type === 'anime' ? 'Total Episode' : editModalMedia.type === 'manga' ? 'Total Chapter' : 'Total Unit' }}
                                </label>
                                <input type="number" v-model.number="editForm.totalUnits" class="w-full bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-700 rounded-lg px-3 py-2 text-sm dark:text-white focus:ring-2 focus:ring-indigo-500">
                            </div>
                        </div>
                    </div>
                </div>

                <div class="px-6 py-5 border-t border-gray-100 dark:border-gray-700 bg-gray-50/50 dark:bg-gray-800/50 flex justify-between items-center">
                    <button @click="deleteMediaHandler(editModalMedia.id)" class="text-xs font-bold text-gray-500 hover:text-red-500 uppercase tracking-wider transition-colors px-2 py-1">Hapus Media</button>
                    <div class="flex gap-2">
                         <button @click="editModalMedia = null" class="px-4 py-2 bg-white dark:bg-gray-700 text-gray-700 dark:text-gray-300 border border-gray-200 dark:border-gray-600 rounded-xl font-bold hover:bg-gray-50 dark:hover:bg-gray-600 transition-colors shadow-sm">Batal</button>
                         <button @click="saveEditMedia" class="px-6 py-2 bg-indigo-600 hover:bg-indigo-500 text-white font-bold rounded-xl transition-colors shadow-sm focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 dark:focus:ring-offset-gray-800">Simpan</button>
                    </div>
                </div>
            </div>
        </div>
        </transition>

    </div>
  `
});
